name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This is just a repo for me to test out websites. They will be shifted to other hoistings when the testing is complete. If you wish to contribute to them, please raise an issue so that it will be transfered to the respective repository.'
        pr-message: 'This is just a repo for me to test out websites. They will be shifted to other hoistings when the testing is complete. If you wish to contribute to them, please raise an issue so that it will be transfered to the respective repository.'
